// <auto-generated />
using System;
using AgroInfoBack.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroInfoBack.Migrations
{
    [DbContext(typeof(AgroContext))]
    [Migration("20241020163549_numeros")]
    partial class numeros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Agrotoxico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("Agrotoxicos");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Fertilizante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("Fertilizantes");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Irrigacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAgendada")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<int>("PlantacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("Irrigacoes");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Plantacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemFim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemMeio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plantacoes");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Agrotoxico", b =>
                {
                    b.HasOne("AgroInfoBack.Models.Agricultura+Plantacao", "Plantacao")
                        .WithMany("Agrotoxicos")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Fertilizante", b =>
                {
                    b.HasOne("AgroInfoBack.Models.Agricultura+Plantacao", "Plantacao")
                        .WithMany("Fertilizantes")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Irrigacao", b =>
                {
                    b.HasOne("AgroInfoBack.Models.Agricultura+Plantacao", "Plantacao")
                        .WithMany("Irrigacoes")
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("AgroInfoBack.Models.Agricultura+Plantacao", b =>
                {
                    b.Navigation("Agrotoxicos");

                    b.Navigation("Fertilizantes");

                    b.Navigation("Irrigacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
